jobs:
  deploy:
    docker:
      - image: cibuilds/hugo
    steps:
      - attach_workspace:
          at: site
      - run: |
            git clone https://${GITHUB_USERNAME}:${DEPLOY_GITHUB_TOKEN}@github.com/alloydwhitlock/whitlock.dev.source.git
            cd whitlock.dev.source
            hugo -v -s . -d public
            cd ..
            git clone https://${GITHUB_USERNAME}:${DEPLOY_GITHUB_TOKEN}@github.com/alloydwhitlock/whitlock.dev.git
            git clone https://${GITHUB_USERNAME}:${DEPLOY_GITHUB_TOKEN}@github.com/alloydwhitlock/alloydwhitlock.github.io.git
            cd whitlock.dev
            git config credential.helper 'cache --timeout=120'
            git config user.email "cicd@whitlock.dev"
            git config user.name "Deployment Bot"
            cp -R ../whitlock.dev.source/public/* .
            git add .
            git commit --allow-empty -m "Trigger deployment via CircleCI"
            git push -q https://${GITHUB_USERNAME}:${DEPLOY_GITHUB_TOKEN}@github.com/alloydwhitlock/whitlock.dev.git master      
            cd ../alloydwhitlock.github.io
            git config credential.helper 'cache --timeout=120'
            git config user.email "cicd@whitlock.dev"
            git config user.name "Deployment Bot"
            cp -R ../whitlock.dev.source/public/* .
            git add .
            git commit --allow-empty -m "Trigger deployment via CircleCI"
            git push -q https://${GITHUB_USERNAME}:${DEPLOY_GITHUB_TOKEN}@github.com/alloydwhitlock/alloydwhitlock.github.io.git      

orbs:
  hugo: circleci/hugo@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          source: src/
          version: '0.58.3'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
