version: 2.1
orbs:
  hugo: circleci/hugo@0.4.1
jobs:
  deploy:
    docker:
      - image: cibuilds/base
    steps:
      - attach_workspace:
          at: my-site
      - run: ls -lah my-site
workflows:
  main:
    jobs:
      - hugo/build:
          version: '0.58.3'
          source: docs/
          html-proofer: true
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
